### ISSUE TITLE
activité “FTW / Fix The Web” (Qui prend?)

### ISSUE THREAD

**Issue by pixeline** [becodeorg/BeCode#3]
Débuguer le web

idée: bescherelletamère.fr #FTW #Becode
http://bescherelletamere.fr/
l'idée est d'envoyer les étudiants à repérer des bugs sur les sites et à trouver la faute et à proposer un fix en tweetant via le compte becode vers le site fautif. #impertinent
un bot 404 en php ?

**Comment by sallartiste** [comment]
**Salut le village,**  @teddykishi @miloon @pixeline 
Je me rend compte que Emily a bien vu lorsqu'elle dit qu'à chaque sujet abordé et traité, on  doit devoir voter pour nous en souvenir. 

A moins de me tromper, mais n'avons nous pas débattu sur le sujet présent, que j'avais d'ailleurs mis sur table? Et à l'issue de ce débat, et après plusieurs discussions et réflexions, nous nous sommes rendu compte que, bien que parti d'une bonne intention, la mise en place de cet exercice n'était pas réaliste. C'est ça ou pas? 

Nous nous sommes dit que l'idée serai bénéfique pour les apprenants que si, le bug trouvé, ils proposent une résolution du bug. Or difficile de proposer une solution tant qu'on ne peut pas remonter à la source. Ensuite comme Teddy l'a montré, certains bugs affichés dans la console, peuvent provenir d'un plug-in ou d'un module installé sur le site, et cela n’empêche pas le site d'être fonction.
L'exemple avec l'API Maps de Google l'a souvent fait.

Alors la question: Doit-on continuer à développer l'exercice malgré notre discussion??? 
Juste aller voir la console du site www.bescherelletamere.fr, un paquet d'erreurs qu'il y a alors qu'ils sont sur wordpress...

**Comment by pixeline** [comment]
@sallartiste pour info, les minutes de la réunion. 
https://docs.google.com/document/d/19zXRKq2V8EJeFUKfCDUKt34Fon97ZjJM866jl_o6bNo/edit

**Comment by miloon** [comment]
Du coup, on laisse tomber ou j'ai pas compris ?
