### ISSUE TITLE
Rédiger notre Checklist des bonnes pratiques & critères de qualité avant de shipper un site/ une app.

### ISSUE THREAD

**Issue by pixeline** [becodeorg/BeCode#5]
voici où le mettre
https://github.com/becodeorg/teacher-only/tree/master/codex

**Comment by miloon** [comment]
[Fichier DWM](https://github.com/becodeorg/teacher-only/blob/master/codex/codex-dwm.md) :

Dans Visual Design, je suis pas sure d'avoir compris le point 1 : est-ce que ça veut dire qu'ils doivent customiser le plug-in ? Par exemple pour une lightbox, changer le background, la font, la vitesse du slide,... ?

Pour le point 2, je me demandais si ce n'était pas une prérogative qui concernerait plus les designer que les dev ?

Est-ce qu'on doit (peut) ajouter aussi au point 2 de Divers, éthique, citoyenneté, qu'il est important de bien respecter la ponctuation également ? (moi par exemple, je repère les sites et mails de qualité/confiance à l'absence de faute d'orthographe et si la ponctuation est impeccable.
#grammarnazi

**Comment by pixeline** [comment]
- oui, mais c parce que ce sont des designers: on veut que le système graphique du site soit cohérent de A à 0. Ici on n'a peut-être pas à avoir la même attente, je ne sais pas. Perso, je trouve que oui mais voilà. on peut pondérer à "pas grave" si ce n'est pas fait (si on garde un système de pondération)

- point 2: exact. N'hésite pas à slasher sauvage. A la limite si tu as un doute, copie/colle les rejets dans un autre fichier corbeille.md, et on décide si on les garde ou pas en #synchrodeformato au vote à majorité qualifiée 🗡 🍡 

Pour l'orthographe, moi je suis pour, mais faut prévoir pour une dizaine chez nous (Santi, et Nadia N par exemple), l'orthographe sera un gros gros problème. Mais pour moi on peut tout de même l'exiger: ils sont prévenus à l'avance, qu'ils organisent des système de relecture.
