### ISSUE TITLE
Link to "badgr on linkedin profile tutorial" broken

### ISSUE THREAD

**Issue by 0ctavia** [becodeorg/BeCode#7]
Just to notify, the link on this page for the "how to put your badgr badges on your linkedIn" is no longer working. Tested the following link in palemoon, chromium and firefox browers : 
https://support.badgr.io/pages/viewpage.action?pageId=4554758

**Comment by webmae** [comment]
Fixed! I change the link towards a post from Alex where he explains two different ways to add a badge on LinkedIn :)
